sap.ui.define(() => ({
    NAV_CHANGED: 'NAV_CHANGED',
    ACTION_SUCCEEDED: 'ACTION_SUCCEEDED',
    ACTION_FAILED: 'ACTION_FAILED',

    TODOLIST_CHANGED: 'TODOLIST_CHANGED',

    TODOPARENT_CHANGED: 'TODOPARENT_CHANGED',

    TODOITEM_CHANGED: 'TODOITEM_CHANGED' 
}));
